### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by Marlon5775** [pclipse/beammp-webgui#1]
I installed BeamMP-WegGUI and i got these errors

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd6 in position 138: invalid continuation byte

Traceback (most recent call last):
  File "C:\Users\Marlon Gamer\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask\app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Marlon Gamer\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask\app.py", line 1476, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Marlon Gamer\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Marlon Gamer\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Marlon Gamer\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Marlon Gamer\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Marlon Gamer\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\BeamMP\app.py", line 154, in index
    config = toml.load(CONFIG_FILE)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Marlon Gamer\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\toml\decoder.py", line 134, in load
    return loads(ffile.read(), _dict, decoder)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd6 in position 138: invalid continuation byte

![grafik](https://github.com/pclipse/beammp-webgui/assets/104256126/eab87c29-f476-4d76-bdf3-3b5c1e64f983)

**Comment by pclipse** [comment]
The UnicodeDecodeError typically occurs when there is an issue with reading a file that contains characters not encoded in UTF-8. This error often arises when dealing with configuration files like TOML, which might contain special characters.

Check the Encoding of ServerConfig.toml: Ensure that ServerConfig.toml is saved with UTF-8 encoding. You can use a text editor like Notepad++ to check and convert the file encoding to UTF-8.

**Comment by Marlon5775** [comment]
I just completely reinstalled the Server+GUI and now it works but still thanks for the effort.

**Comment by Marlon5775** [comment]
But i still have an question. Is there a way that i can see the terminal outputs in the webgui?

**Comment by pclipse** [comment]
There probably is a way, but I'd need to recreate or edit the GUI for it to
have the. I don't mind looking into it though
